[package]
name = "gestalt"
version = "0.1.0"
authors = ["trstruth <trstruth@microsoft.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
kdtree= "0.6.0"
rand = "0.7.2"
clap = "2.33.3"
